package lol.simeon.bl3;

public enum CommandPrefixes {
  SELECT_PRINT_START_TRIGGER("^PT!"),
  START_PRINTING("^FF"),
  SPECIFY_PRINT_START_COMMAND_TEXT_STRING("^PS!!@"),
  SPECIFY_PRINT_START_RECEIVED_CHARACTER_COUNT("^PC!!!"),
  SPECIFY_DELIMITER("^SS!!@"),
  SELECT_TEMPLATE("^TS0!!"),
  SPECIFY_LINE_SPACING("^LS!!!"),
  CHANGE_PREFIX_CHARACTER("^CC!"),
  SPECIFY_LINE_FEED_TEXT("^RC!!@"),
  SPECIFY_NUMBER_OF_COPIES("^CN!!!"),
  SPECIFY_NUMBERING_COPIES("^NN!!!"),
  INITIALIZE_TEMPLATE("^ID"),
  SELECT_PRINT_OPTIONS("^QS!"),
  SPECIFY_QR_CODE_VERSION("^QV!!"),
  FNC1_REPLACEMENT_SETTING("^FC!"),
  FULL_CUT_SETTING("^CF!!"),
  HALF_CUT_SETTING("^CH!"),
  CHAIN_PRINTING_SETTING("^CP!"),
  MIRROR_PRINTING_SETTING("^MP!"),
  INITIALIZE("^II"),
  PERFORM_MACHINE_OPERATION("^OP!"),
  STATUS_REQUEST("^SR"),
  RETRIEVE_VERSION("^VR"),
  LINE_FEED_IN_OBJECT("^CR"),
  SELECT_OBJECT_BY_NUMBER("^OS!!"),
  SELECT_OBJECT_BY_NAME("^ON@"),
  DIRECTLY_INSERT_OBJECT("^DI!!@"),
  SPECIFY_COMMAND_MODE("ESCia!")
  ;
  private final String prefix;

  CommandPrefixes(String prefix) {
    this.prefix = prefix;
  }

  public String getPrefix() {
    return prefix;
  }
}
